# Generated by Django 4.1.4 on 2022-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('transcript', models.TextField()),
                ('slug', models.CharField(db_index=True, max_length=400, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('language', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('thumbnail', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('tags', models.ManyToManyField(to='converter.tagsmodel')),
            ],
        ),
    ]
